# Week 1 Assignment: Housing Prices

In this exercise you'll try to build a neural network that predicts the price of a house according to a simple formula.

Imagine that house pricing is as easy as:

A house has a base cost of 50k, and every additional bedroom adds a cost of 50k. This will make a 1 bedroom house cost 100k, a 2 bedroom house cost 150k etc.

How would you create a neural network that learns this relationship so that it would predict a 7 bedroom house as costing close to 400k etc.

Hint: Your network might work better if you scale the house price down. You don't have to give the answer 400...it might be better to create something that predicts the number 4, and then your answer is in the 'hundreds of thousands' etc.

In [1]:
import keras
import numpy as np

In [14]:
# GRADED FUNCTION: house_model
def normalize(ys):
    return xs,ys*0.01
def un_normalize(ys):
    return xs.,ys*100.
def house_model():
    ### START CODE HERE
    
    # Define input and output tensors with the values for houses with 1 up to 6 bedrooms
    # Hint: Remember to explictly set the dtype as float
    #xs:number of bedrooms
    xs = np.arange(6,dtype=float)
    #ys:cost of house
    ys = 50+50*xs

    print(xs)
    print(ys)
    xs,ys=normalize(xs,ys)
    print(xs)
    print(ys)
    # Define your model (should be a model with 1 dense layer and 1 unit)
    model = keras.Sequential([keras.layers.Dense(units=1,input_shape=[1])])
    
    # Compile your model
    # Set the optimizer to Stochastic Gradient Descent
    # and use Mean Squared Error as the loss function
    model.compile(optimizer='sgd',loss='mean_squared_error')
    
    # Train your model for 1000 epochs by feeding the i/o tensors
    model.fit(xs,ys,epochs=1000)
    
    ### END CODE HERE
    return model

Now that you have a function that returns a compiled and trained model when invoked, use it to get the model to predict the price of houses: 

In [15]:
# Get your trained model
model = house_model()

[0. 1. 2. 3. 4. 5.]
[ 50. 100. 150. 200. 250. 300.]
[0. 1. 2. 3. 4. 5.]
[0.5 1.  1.5 2.  2.5 3. ]
Epoch 1/1000
1/1 [==============================] - 0s 125ms/step - loss: 0.1688
Epoch 2/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1389
Epoch 3/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1193
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1063
Epoch 5/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0976
Epoch 6/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0917
Epoch 7/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0875
Epoch 8/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0845
Epoch 9/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0822
Epoch 10/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0804
Epoch 11/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0789
Epoch 12/1000
1/1 [

1/1 [==============================] - 0s 998us/step - loss: 0.0271
Epoch 101/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0268
Epoch 102/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0265
Epoch 103/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0262
Epoch 104/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0259
Epoch 105/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0256
Epoch 106/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0253
Epoch 107/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0250
Epoch 108/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0247
Epoch 109/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0244
Epoch 110/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0241
Epoch 111/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0238
Epoch 112/1000
1/1 [=

1/1 [==============================] - 0s 997us/step - loss: 0.0084
Epoch 200/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0083
Epoch 201/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0082
Epoch 202/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0081
Epoch 203/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0080
Epoch 204/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0079
Epoch 205/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0078
Epoch 206/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0077
Epoch 207/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0076
Epoch 208/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0075
Epoch 209/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0075
Epoch 210/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0074
Epoch 211/1000
1/1 [=

1/1 [==============================] - 0s 998us/step - loss: 0.0026
Epoch 299/1000
1/1 [==============================] - 0s 0s/step - loss: 0.0026
Epoch 300/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0025
Epoch 301/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0025
Epoch 302/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0025
Epoch 303/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0024
Epoch 304/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0024
Epoch 305/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0024
Epoch 306/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0024
Epoch 307/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0023
Epoch 308/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0023
Epoch 309/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0023
Epoch 310/1000
1/1 [======

1/1 [==============================] - 0s 2ms/step - loss: 8.1247e-04
Epoch 397/1000
1/1 [==============================] - 0s 998us/step - loss: 8.0289e-04
Epoch 398/1000
1/1 [==============================] - 0s 997us/step - loss: 7.9343e-04
Epoch 399/1000
1/1 [==============================] - 0s 997us/step - loss: 7.8408e-04
Epoch 400/1000
1/1 [==============================] - 0s 998us/step - loss: 7.7484e-04
Epoch 401/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.6571e-04
Epoch 402/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.5669e-04
Epoch 403/1000
1/1 [==============================] - 0s 998us/step - loss: 7.4777e-04
Epoch 404/1000
1/1 [==============================] - 0s 997us/step - loss: 7.3896e-04
Epoch 405/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.3025e-04
Epoch 406/1000
1/1 [==============================] - 0s 997us/step - loss: 7.2164e-04
Epoch 407/1000
1/1 [==============================] - 0s 997us/ste

1/1 [==============================] - 0s 998us/step - loss: 2.6662e-04
Epoch 491/1000
1/1 [==============================] - 0s 998us/step - loss: 2.6347e-04
Epoch 492/1000
1/1 [==============================] - 0s 997us/step - loss: 2.6037e-04
Epoch 493/1000
1/1 [==============================] - 0s 998us/step - loss: 2.5730e-04
Epoch 494/1000
1/1 [==============================] - 0s 997us/step - loss: 2.5427e-04
Epoch 495/1000
1/1 [==============================] - 0s 997us/step - loss: 2.5127e-04
Epoch 496/1000
1/1 [==============================] - 0s 998us/step - loss: 2.4831e-04
Epoch 497/1000
1/1 [==============================] - 0s 997us/step - loss: 2.4539e-04
Epoch 498/1000
1/1 [==============================] - 0s 997us/step - loss: 2.4249e-04
Epoch 499/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.3964e-04
Epoch 500/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.3681e-04
Epoch 501/1000
1/1 [==============================] - 0s 2ms/s

1/1 [==============================] - 0s 997us/step - loss: 8.7491e-05
Epoch 585/1000
1/1 [==============================] - 0s 998us/step - loss: 8.6460e-05
Epoch 586/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.5441e-05
Epoch 587/1000
1/1 [==============================] - 0s 998us/step - loss: 8.4434e-05
Epoch 588/1000
1/1 [==============================] - 0s 998us/step - loss: 8.3439e-05
Epoch 589/1000
1/1 [==============================] - 0s 997us/step - loss: 8.2456e-05
Epoch 590/1000
1/1 [==============================] - 0s 998us/step - loss: 8.1484e-05
Epoch 591/1000
1/1 [==============================] - 0s 998us/step - loss: 8.0524e-05
Epoch 592/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.9575e-05
Epoch 593/1000
1/1 [==============================] - 0s 997us/step - loss: 7.8638e-05
Epoch 594/1000
1/1 [==============================] - 0s 998us/step - loss: 7.7711e-05
Epoch 595/1000
1/1 [==============================] - 0s 2ms/s

1/1 [==============================] - 0s 997us/step - loss: 2.8711e-05
Epoch 679/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.8372e-05
Epoch 680/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.8038e-05
Epoch 681/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.7708e-05
Epoch 682/1000
1/1 [==============================] - 0s 998us/step - loss: 2.7382e-05
Epoch 683/1000
1/1 [==============================] - 0s 997us/step - loss: 2.7059e-05
Epoch 684/1000
1/1 [==============================] - 0s 997us/step - loss: 2.6740e-05
Epoch 685/1000
1/1 [==============================] - 0s 997us/step - loss: 2.6425e-05
Epoch 686/1000
1/1 [==============================] - 0s 998us/step - loss: 2.6114e-05
Epoch 687/1000
1/1 [==============================] - 0s 998us/step - loss: 2.5806e-05
Epoch 688/1000
1/1 [==============================] - 0s 997us/step - loss: 2.5502e-05
Epoch 689/1000
1/1 [==============================] - 0s 2ms/ste

1/1 [==============================] - 0s 997us/step - loss: 9.4217e-06
Epoch 773/1000
1/1 [==============================] - 0s 998us/step - loss: 9.3108e-06
Epoch 774/1000
1/1 [==============================] - 0s 998us/step - loss: 9.2010e-06
Epoch 775/1000
1/1 [==============================] - 0s 997us/step - loss: 9.0926e-06
Epoch 776/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.9855e-06
Epoch 777/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.8797e-06
Epoch 778/1000
1/1 [==============================] - 0s 998us/step - loss: 8.7752e-06
Epoch 779/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.6716e-06
Epoch 780/1000
1/1 [==============================] - 0s 998us/step - loss: 8.5695e-06
Epoch 781/1000
1/1 [==============================] - 0s 998us/step - loss: 8.4681e-06
Epoch 782/1000
1/1 [==============================] - 0s 997us/step - loss: 8.3685e-06
Epoch 783/1000
1/1 [==============================] - 0s 998us/s

1/1 [==============================] - 0s 998us/step - loss: 3.0918e-06
Epoch 867/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.0554e-06
Epoch 868/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.0194e-06
Epoch 869/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.9839e-06
Epoch 870/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.9487e-06
Epoch 871/1000
1/1 [==============================] - 0s 998us/step - loss: 2.9139e-06
Epoch 872/1000
1/1 [==============================] - 0s 998us/step - loss: 2.8797e-06
Epoch 873/1000
1/1 [==============================] - 0s 997us/step - loss: 2.8457e-06
Epoch 874/1000
1/1 [==============================] - 0s 998us/step - loss: 2.8121e-06
Epoch 875/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.7790e-06
Epoch 876/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.7462e-06
Epoch 877/1000
1/1 [==============================] - 0s 998us/step - 

1/1 [==============================] - 0s 997us/step - loss: 1.0146e-06
Epoch 961/1000
1/1 [==============================] - 0s 998us/step - loss: 1.0026e-06
Epoch 962/1000
1/1 [==============================] - 0s 997us/step - loss: 9.9074e-07
Epoch 963/1000
1/1 [==============================] - 0s 997us/step - loss: 9.7912e-07
Epoch 964/1000
1/1 [==============================] - 0s 997us/step - loss: 9.6758e-07
Epoch 965/1000
1/1 [==============================] - 0s 997us/step - loss: 9.5620e-07
Epoch 966/1000
1/1 [==============================] - 0s 997us/step - loss: 9.4487e-07
Epoch 967/1000
1/1 [==============================] - 0s 2ms/step - loss: 9.3379e-07
Epoch 968/1000
1/1 [==============================] - 0s 2ms/step - loss: 9.2282e-07
Epoch 969/1000
1/1 [==============================] - 0s 998us/step - loss: 9.1199e-07
Epoch 970/1000
1/1 [==============================] - 0s 997us/step - loss: 9.0120e-07
Epoch 971/1000
1/1 [==============================] - 0s 2ms/s

Now that your model has finished training it is time to test it out! You can do so by running the next cell.

In [16]:
new_x = 7.0
prediction = model.predict([new_x])[0]*100.
print(50+7*50)
print(prediction)

400
[400.13605]


If everything went as expected you should see a prediction value very close to 4. **If not, try adjusting your code before submitting the assignment.** Notice that you can play around with the value of `new_y` to get different predictions. In general you should see that the network was able to learn the linear relationship between `x` and `y`, so if you use a value of 8.0 you should get a prediction close to 4.5 and so on.

**Congratulations on finishing this week's assignment!**

You have successfully coded a neural network that learned the linear relationship between two variables. Nice job!

**Keep it up!**